# Generated by Django 4.2.16 on 2024-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('1', 'FCFS'), ('2', 'RR'), ('3', 'SJF'), ('4', 'SRT')], max_length=1)),
            ],
        ),
    ]
