# Generated by Django 4.2.16 on 2024-11-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Number of processes (between 1 and 9)', verbose_name='Number of processes')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FcfsProcessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.PositiveIntegerField(verbose_name='execution time')),
                ('fcfs_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcfs_algorithms', to='home.countmodel')),
            ],
        ),
    ]
