# Generated by Django 4.2.16 on 2024-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_countmodel_fcfsprocessmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicProcessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('burst_time', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fcfsprocessmodel',
            name='fcfs_algorithm',
        ),
        migrations.DeleteModel(
            name='CountModel',
        ),
        migrations.DeleteModel(
            name='FcfsProcessModel',
        ),
    ]
