# Generated by Django 4.2.16 on 2024-12-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dynamicprocessmodel_quantum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicprocessmodel',
            name='priority',
        ),
    ]
