# Generated by Django 4.2.16 on 2024-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_dynamicprocessmodel_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantum', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='dynamicprocessmodel',
            name='quantum',
        ),
    ]
